name: Balea Continous Integration
on:
  push:
    branches:
      - release/*
      - feature/*
      - fix/*

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
          - 5433:1433
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core SDK 6.0.424
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.424
      - name: Setup .NET Core SDK 8.0.303
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.303
          
      - name: dotnet build  dotNET 6.0
        run: dotnet build Balea.sln -c $BUILD_CONFIG --framework net6.0
      - name: dotnet build  dotNET 8.0
        run: dotnet build Balea.sln -c $BUILD_CONFIG --framework net8.0        
      - name: dotnet test [FunctionalTests]
        run: dotnet test ./test/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
