name: Balea continous Deployment (PREVIEW)
on:
  push:
    tags:
      - preview*

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -preview${{ github.run_number }}
    name: Build
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
          - 5433:1433
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core SDK 6.0.200
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.200
      - name: Setup .NET Core SDK 5.0.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Setup .NET Core SDK 3.1.301
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.404
      - name: dotnet build
        run: dotnet build Balea.sln -c $BUILD_CONFIG
      - name: dotnet test [FunctionalTests]
        run: dotnet test ./test/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
      - name: dotnet pack [Balea]
        run: dotnet pack ./src/Balea/Balea.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: dotnet pack [Balea.Grantor.Configuration]
        run: dotnet pack ./src/Balea.Grantor.Configuration/Balea.Grantor.Configuration.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: dotnet pack [Balea.Grantor.EntityFrameworkCore]
        run: dotnet pack ./src/Balea.Grantor.EntityFrameworkCore/Balea.Grantor.EntityFrameworkCore.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: dotnet pack [Balea.Grantor.Api]
        run: dotnet pack ./src/Balea.Grantor.Api/Balea.Grantor.Api.csproj -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols -o ./artifacts
      - name: setup nuget
        uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: latest
      - name: Publish Balea nuget
        run: dotnet nuget push ./artifacts/Balea.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish Configuration Store nuget
        run: dotnet nuget push ./artifacts/Balea.Grantor.Configuration.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish EntityFramework Store  nuget
        run: dotnet nuget push ./artifacts/Balea.Grantor.EntityFrameworkCore.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - name: Publish Api Store nuget
        run: dotnet nuget push ./artifacts/Balea.Grantor.Api.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
